# Generated by Django 6.0 on 2026-02-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_bolim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('candidate', 'Ish izlovchi'), ('employer', 'Ish beruvchi'), ('admin', 'Admin')], max_length=20),
        ),
    ]
