# Generated by Django 6.0 on 2026-02-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_bolim', '0003_candidateprofile_education_experience_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, help_text='Total years of experience'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Default CV for 1-click apply', null=True, upload_to='resumes/default/'),
        ),
    ]
