# Generated by Django 6.0 on 2026-02-17 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_bolim', '0004_candidateprofile_experience_years_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='CV nomi (masalan: Python Developer CV)', max_length=150)),
                ('file', models.FileField(upload_to='resumes/user_uploads/')),
                ('is_public', models.BooleanField(default=True, help_text="Boshqa ish beruvchilar ko'ra oladimi?")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
