# Generated by Django 6.0 on 2026-02-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_bolim', '0006_job_experience_required_job_salary_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='is_processing_restricted',
            field=models.BooleanField(default=False, help_text='User restricted data processing'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('interview', 'Interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
