# Generated by Django 6.0 on 2026-02-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_bolim', '0011_add_admin_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('candidate', 'Ish izlovchi'), ('employer', 'Ish beruvchi'), ('admin', 'Admin')], default='candidate', max_length=20),
        ),
    ]
